### ISSUE TITLE
zctl under MacOS

### ISSUE THREAD

**Issue by PRESFIL** [natesales/zctl#1]
I'm not MacOS user and cannot test difference between Linux and MacOS `bash`/`environment`, but `zctl` is such plain script, and already get troubles in porting?

Do you use MacOS? Is cross-platform important?

**Comment by natesales** [comment]
The `zctl` bash script will work fine as it's just bash, but the underlying zctl virtual webcam won't work under MacOS as it relies on v4l2loopback which is specific to the linux kernel. So unfortunately zctl is a linux-only application at the moment.

**Comment by PRESFIL** [comment]
Ok, i thought so :smile:. I see several opportunities for improvement. But I didn't want to add unverified code.
